networks:
  guacnetwork_compose:
    driver: bridge

services:
  # guacd (no changes)
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  
  # postgres (no changes)
  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  # guacamole (no changes)
  guacamole:
    container_name: guacamole_compose
    hostname: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      RECORDING_SEARCH_PATH: /record
    image: guacamole/guacamole
    networks:
      - guacnetwork_compose
    volumes:
      - ./record:/record:rw
    ports:
    - 8080/tcp
    restart: always

  # nginx (FIXED)
  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    networks:
      - guacnetwork_compose
    volumes:
      # Mount the new entrypoint script and make it available inside the container.
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/templates:/etc/nginx/templates
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    # REMOVE the old 'command' key entirely.
    # ADD the new 'entrypoint' key to run our script.
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      - guacamole
    restart: always
  # certbot (no changes)
  certbot:
    image: certbot/certbot
    networks:
      - guacnetwork_compose
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    env_file:
      - ./.env
    # --- FIX: REMOVED the conflicting 'command' key ---
    # command: "renew"  <-- This line is now deleted.
    

volumes:
  certbot_certs:
  certbot_www: